React tutorial - Todo App
bobb-Rob/react-todo-app pull request #2
Opened 2022-07-05 08:08 UTC by bobb-Rob

## Implemented the following:

- Created five components using classbased function at first.
- Refactor all components to functionbased component

2022-07-06 21:35 UTC, jadibdev requested changes

2022-07-06 21:35 UTC, jadibdev commented on src/classBased/components/header.js
> +            textAlign: "center",
Kindly use an external file for your CSS as it would make your components cleaner and your code more organized overall.

2022-07-06 21:35 UTC, jadibdev commented on src/index.js
> -import reportWebVitals from './reportWebVitals';
Kindly remove this import along with reportWebVitals.js and any other boilerplate code in the src folder

2022-07-06 21:35 UTC, jadibdev commented on src/index.js
> -reportWebVitals();
Kindly remove comments along with function call as they are irrelevant to this project and make your code look messier.

2022-07-07 12:14 UTC, bobb-Rob commented on src/classBased/components/header.js
> +            textAlign: "center",
Thank You I have implemented the this

2022-07-07 12:16 UTC, bobb-Rob commented on src/index.js
> -import reportWebVitals from './reportWebVitals';
Thank you very much. But this was already removed, it is red with minus

2022-07-07 12:16 UTC, bobb-Rob commented on src/index.js
> -reportWebVitals();
Thank you very much. Done

2022-07-07 13:29 UTC, jadibdev approved these changes

2022-07-07 13:37 UTC, merged